[workspace]
members = [
    "libudev-sys",
    "libinput-sys",
    "libseat-sys",
    "gbm-sys",
    "drm-sys",
    "libxkbcommon-sys",
    "wayland-sys",
    "libdisplay-info-sys",
    "libei-sys",
    "libdbus-sys",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"

[workspace.dependencies]
libc = "0.2"
libloading = "0.8"
bindgen = "0.69"
